# Parsed denial constraints for Adult
# Generated automatically from raw constraints

denial_constraints = [
    [('t1.education', '!=', 't2.education'), ('t1.education-num', '==', 't2.education-num')],
    [('t1.education', '==', 't2.education'), ('t1.education-num', '!=', 't2.education-num')],
    [('t1.education', '==', 't2.education'), ('t1.education-num', '>', 't2.education-num')],
    [('t1.education', '==', 't2.education'), ('t1.education-num', '<', 't2.education-num')],
    [('t1.capital-gain', '>', 't2.capital-gain'), ('t1.capital-loss', '>', 't2.capital-loss')],
    [('t1.capital-gain', '<', 't2.capital-gain'), ('t1.capital-loss', '<', 't2.capital-loss')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex'), ('t1.native-country', '==', 't2.native-country')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.relationship', '==', 't2.relationship'), ('t1.race', '==', 't2.race'), ('t1.sex', '!=', 't2.sex')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education', '==', 't2.education'), ('t1.occupation', '!=', 't2.occupation'), ('t1.race', '!=', 't2.race')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education-num', '==', 't2.education-num'), ('t1.occupation', '!=', 't2.occupation'), ('t1.race', '!=', 't2.race')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.marital-status', '!=', 't2.marital-status'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.sex', '!=', 't2.sex'), ('t1.capital-gain', '!=', 't2.capital-gain'), ('t1.hours-per-week', '!=', 't2.hours-per-week')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education', '!=', 't2.education'), ('t1.occupation', '==', 't2.occupation'), ('t1.sex', '!=', 't2.sex')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education-num', '!=', 't2.education-num'), ('t1.occupation', '==', 't2.occupation'), ('t1.sex', '!=', 't2.sex')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education', '==', 't2.education'), ('t1.race', '!=', 't2.race'), ('t1.native-country', '==', 't2.native-country')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education-num', '==', 't2.education-num'), ('t1.race', '!=', 't2.race'), ('t1.native-country', '==', 't2.native-country')],
    [('t1.age', '==', 't2.age'), ('t1.workclass', '!=', 't2.workclass'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.race', '!=', 't2.race'), ('t1.sex', '!=', 't2.sex')],
    [('t1.age', '==', 't2.age'), ('t1.workclass', '!=', 't2.workclass'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.relationship', '!=', 't2.relationship'), ('t1.race', '!=', 't2.race'), ('t1.capital-loss', '!=', 't2.capital-loss')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education', '==', 't2.education'), ('t1.race', '!=', 't2.race'), ('t1.class', '==', 't2.class')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education-num', '==', 't2.education-num'), ('t1.race', '!=', 't2.race'), ('t1.class', '==', 't2.class')],
    [('t1.age', '==', 't2.age'), ('t1.workclass', '!=', 't2.workclass'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.sex', '!=', 't2.sex'), ('t1.capital-gain', '!=', 't2.capital-gain')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.race', '!=', 't2.race'), ('t1.sex', '!=', 't2.sex'), ('t1.class', '!=', 't2.class')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.race', '!=', 't2.race'), ('t1.capital-gain', '!=', 't2.capital-gain'), ('t1.class', '==', 't2.class')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.sex', '!=', 't2.sex'), ('t1.capital-gain', '>', 't2.capital-gain'), ('t1.hours-per-week', '!=', 't2.hours-per-week')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.sex', '!=', 't2.sex'), ('t1.capital-gain', '<', 't2.capital-gain'), ('t1.hours-per-week', '!=', 't2.hours-per-week')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex'), ('t1.class', '!=', 't2.class')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.marital-status', '!=', 't2.marital-status'), ('t1.race', '!=', 't2.race'), ('t1.capital-loss', '!=', 't2.capital-loss')],
    [('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex'), ('t1.capital-gain', '!=', 't2.capital-gain'), ('t1.native-country', '!=', 't2.native-country')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.occupation', '==', 't2.occupation'), ('t1.race', '!=', 't2.race'), ('t1.class', '==', 't2.class')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education', '==', 't2.education'), ('t1.marital-status', '==', 't2.marital-status'), ('t1.sex', '!=', 't2.sex')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education-num', '==', 't2.education-num'), ('t1.marital-status', '==', 't2.marital-status'), ('t1.sex', '!=', 't2.sex')],
    [('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex'), ('t1.capital-loss', '!=', 't2.capital-loss'), ('t1.native-country', '!=', 't2.native-country')],
    [('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.occupation', '==', 't2.occupation'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex'), ('t1.native-country', '!=', 't2.native-country')],
    [('t1.age', '==', 't2.age'), ('t1.workclass', '!=', 't2.workclass'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education', '==', 't2.education'), ('t1.race', '!=', 't2.race')],
    [('t1.age', '==', 't2.age'), ('t1.workclass', '!=', 't2.workclass'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.education-num', '==', 't2.education-num'), ('t1.race', '!=', 't2.race')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.sex', '!=', 't2.sex'), ('t1.capital-gain', '!=', 't2.capital-gain'), ('t1.class', '!=', 't2.class')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex'), ('t1.hours-per-week', '==', 't2.hours-per-week')],
    [('t1.age', '==', 't2.age'), ('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.marital-status', '==', 't2.marital-status'), ('t1.sex', '!=', 't2.sex'), ('t1.capital-gain', '!=', 't2.capital-gain')],
    [('t1.fnlwgt', '==', 't2.fnlwgt'), ('t1.occupation', '==', 't2.occupation'), ('t1.relationship', '==', 't2.relationship'), ('t1.sex', '!=', 't2.sex'), ('t1.capital-gain', '!=', 't2.capital-gain')],
]
