# Parsed denial constraints for Hospital
# Generated automatically from raw constraints

denial_constraints = [
    [('t1.measurecode', '!=', 't2.measurecode'), ('t1.measurename', '==', 't2.measurename')],
    [('t1.measurecode', '==', 't2.measurecode'), ('t1.measurename', '!=', 't2.measurename')],
    [('t1.providernumber', '==', 't2.providernumber'), ('t1.phonenumber', '!=', 't2.phonenumber')],
    [('t1.providernumber', '==', 't2.providernumber'), ('t1.hospitalname', '!=', 't2.hospitalname')],
    [('t1.zipcode', '!=', 't2.zipcode'), ('t1.phonenumber', '==', 't2.phonenumber')],
    [('t1.providernumber', '==', 't2.providernumber'), ('t1.zipcode', '!=', 't2.zipcode')],
    [('t1.measurecode', '!=', 't2.measurecode'), ('t1.stateavg', '==', 't2.stateavg')],
    [('t1.measurename', '!=', 't2.measurename'), ('t1.stateavg', '==', 't2.stateavg')],
    [('t1.city', '!=', 't2.city'), ('t1.zipcode', '==', 't2.zipcode')],
    [('t1.city', '!=', 't2.city'), ('t1.phonenumber', '==', 't2.phonenumber')],
    [('t1.providernumber', '==', 't2.providernumber'), ('t1.city', '!=', 't2.city')],
    [('t1.providernumber', '==', 't2.providernumber'), ('t1.countyname', '!=', 't2.countyname')],
    [('t1.providernumber', '==', 't2.providernumber'), ('t1.hospitalowner', '!=', 't2.hospitalowner')],
    [('t1.state', '==', 't2.state'), ('t1.measurename', '==', 't2.measurename'), ('t1.stateavg', '!=', 't2.stateavg')],
    [('t1.state', '==', 't2.state'), ('t1.measurecode', '==', 't2.measurecode'), ('t1.stateavg', '!=', 't2.stateavg')],
    [('t1.condition', '!=', 't2.condition'), ('t1.measurecode', '==', 't2.measurecode')],
    [('t1.condition', '!=', 't2.condition'), ('t1.measurename', '==', 't2.measurename')],
    [('t1.condition', '!=', 't2.condition'), ('t1.stateavg', '==', 't2.stateavg')],
    [('t1.providernumber', '==', 't2.providernumber'), ('t1.measurecode', '==', 't2.measurecode')],
    [('t1.providernumber', '==', 't2.providernumber'), ('t1.measurename', '==', 't2.measurename')],
    [('t1.providernumber', '==', 't2.providernumber'), ('t1.stateavg', '==', 't2.stateavg')],
    [('t1.providernumber', '==', 't2.providernumber'), ('t1.emergencyservice', '!=', 't2.emergencyservice')],
    [('t1.zipcode', '==', 't2.zipcode'), ('t1.countyname', '!=', 't2.countyname'), ('t1.phonenumber', '!=', 't2.phonenumber'), ('t1.hospitalowner', '==', 't2.hospitalowner')],
    [('t1.hospitalname', '==', 't2.hospitalname'), ('t1.state', '==', 't2.state'), ('t1.hospitalowner', '!=', 't2.hospitalowner'), ('t1.emergencyservice', '!=', 't2.emergencyservice')],
    [('t1.providernumber', '!=', 't2.providernumber'), ('t1.hospitalname', '==', 't2.hospitalname'), ('t1.city', '==', 't2.city'), ('t1.state', '==', 't2.state')],
    [('t1.hospitalname', '==', 't2.hospitalname'), ('t1.city', '==', 't2.city'), ('t1.state', '==', 't2.state'), ('t1.phonenumber', '!=', 't2.phonenumber')],
    [('t1.hospitalname', '==', 't2.hospitalname'), ('t1.city', '==', 't2.city'), ('t1.state', '==', 't2.state'), ('t1.zipcode', '!=', 't2.zipcode')],
    [('t1.zipcode', '==', 't2.zipcode'), ('t1.measurecode', '==', 't2.measurecode'), ('t1.stateavg', '!=', 't2.stateavg')],
    [('t1.zipcode', '==', 't2.zipcode'), ('t1.measurename', '==', 't2.measurename'), ('t1.stateavg', '!=', 't2.stateavg')],
    [('t1.phonenumber', '==', 't2.phonenumber'), ('t1.measurecode', '==', 't2.measurecode'), ('t1.stateavg', '!=', 't2.stateavg')],
    [('t1.phonenumber', '==', 't2.phonenumber'), ('t1.measurename', '==', 't2.measurename'), ('t1.stateavg', '!=', 't2.stateavg')],
    [('t1.providernumber', '!=', 't2.providernumber'), ('t1.hospitalname', '==', 't2.hospitalname'), ('t1.zipcode', '==', 't2.zipcode')],
    [('t1.hospitalname', '==', 't2.hospitalname'), ('t1.zipcode', '==', 't2.zipcode'), ('t1.phonenumber', '!=', 't2.phonenumber')],
    [('t1.providernumber', '!=', 't2.providernumber'), ('t1.hospitalname', '==', 't2.hospitalname'), ('t1.phonenumber', '==', 't2.phonenumber')],
    [('t1.hospitalname', '==', 't2.hospitalname'), ('t1.city', '==', 't2.city'), ('t1.state', '==', 't2.state'), ('t1.countyname', '!=', 't2.countyname')],
    [('t1.hospitalname', '==', 't2.hospitalname'), ('t1.zipcode', '==', 't2.zipcode'), ('t1.countyname', '!=', 't2.countyname')],
    [('t1.hospitalname', '==', 't2.hospitalname'), ('t1.countyname', '!=', 't2.countyname'), ('t1.phonenumber', '==', 't2.phonenumber')],
    [('t1.hospitalname', '==', 't2.hospitalname'), ('t1.state', '==', 't2.state'), ('t1.countyname', '==', 't2.countyname'), ('t1.hospitalowner', '!=', 't2.hospitalowner')],
    [('t1.hospitalname', '==', 't2.hospitalname'), ('t1.city', '==', 't2.city'), ('t1.state', '==', 't2.state'), ('t1.hospitalowner', '!=', 't2.hospitalowner')],
    [('t1.state', '!=', 't2.state'), ('t1.stateavg', '==', 't2.stateavg')],
]
