# Parsed denial constraints for Tax
# Generated automatically from raw constraints

denial_constraints = [
    [('t1.city', '!=', 't2.city'), ('t1.zip', '==', 't2.zip')],
    [('t1.areacode', '==', 't2.areacode'), ('t1.state', '!=', 't2.state')],
    [('t1.state', '!=', 't2.state'), ('t1.zip', '==', 't2.zip')],
    [('t1.singleexemp', '>', 't2.singleexemp'), ('t1.marriedexemp', '>', 't2.marriedexemp')],
    [('t1.singleexemp', '<', 't2.singleexemp'), ('t1.marriedexemp', '<', 't2.marriedexemp')],
    [('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '!=', 't2.singleexemp'), ('t1.marriedexemp', '!=', 't2.marriedexemp')],
    [('t1.fname', '==', 't2.fname'), ('t1.gender', '!=', 't2.gender')],
    [('t1.areacode', '==', 't2.areacode'), ('t1.phone', '==', 't2.phone')],
    [('t1.phone', '==', 't2.phone'), ('t1.city', '==', 't2.city')],
    [('t1.fname', '==', 't2.fname'), ('t1.phone', '==', 't2.phone')],
    [('t1.lname', '==', 't2.lname'), ('t1.phone', '==', 't2.phone')],
    [('t1.phone', '==', 't2.phone'), ('t1.zip', '==', 't2.zip')],
    [('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '!=', 't2.singleexemp'), ('t1.marriedexemp', '>', 't2.marriedexemp')],
    [('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '!=', 't2.singleexemp'), ('t1.marriedexemp', '<', 't2.marriedexemp')],
    [('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '>', 't2.singleexemp'), ('t1.marriedexemp', '!=', 't2.marriedexemp')],
    [('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '<', 't2.singleexemp'), ('t1.marriedexemp', '!=', 't2.marriedexemp')],
    [('t1.state', '==', 't2.state'), ('t1.haschild', '==', 't2.haschild'), ('t1.childexemp', '!=', 't2.childexemp')],
    [('t1.areacode', '==', 't2.areacode'), ('t1.haschild', '==', 't2.haschild'), ('t1.childexemp', '!=', 't2.childexemp')],
    [('t1.state', '==', 't2.state'), ('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '!=', 't2.singleexemp')],
    [('t1.state', '==', 't2.state'), ('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.marriedexemp', '!=', 't2.marriedexemp')],
    [('t1.zip', '==', 't2.zip'), ('t1.haschild', '==', 't2.haschild'), ('t1.childexemp', '!=', 't2.childexemp')],
    [('t1.areacode', '==', 't2.areacode'), ('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '!=', 't2.singleexemp')],
    [('t1.areacode', '==', 't2.areacode'), ('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.marriedexemp', '!=', 't2.marriedexemp')],
    [('t1.zip', '==', 't2.zip'), ('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '!=', 't2.singleexemp')],
    [('t1.zip', '==', 't2.zip'), ('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.marriedexemp', '!=', 't2.marriedexemp')],
    [('t1.state', '==', 't2.state'), ('t1.singleexemp', '!=', 't2.singleexemp'), ('t1.marriedexemp', '==', 't2.marriedexemp')],
    [('t1.state', '==', 't2.state'), ('t1.singleexemp', '==', 't2.singleexemp'), ('t1.marriedexemp', '!=', 't2.marriedexemp')],
    [('t1.areacode', '==', 't2.areacode'), ('t1.singleexemp', '!=', 't2.singleexemp'), ('t1.marriedexemp', '==', 't2.marriedexemp')],
    [('t1.state', '==', 't2.state'), ('t1.salary', '==', 't2.salary'), ('t1.rate', '!=', 't2.rate')],
    [('t1.areacode', '==', 't2.areacode'), ('t1.singleexemp', '==', 't2.singleexemp'), ('t1.marriedexemp', '!=', 't2.marriedexemp')],
    [('t1.zip', '==', 't2.zip'), ('t1.singleexemp', '!=', 't2.singleexemp'), ('t1.marriedexemp', '==', 't2.marriedexemp')],
    [('t1.zip', '==', 't2.zip'), ('t1.singleexemp', '==', 't2.singleexemp'), ('t1.marriedexemp', '!=', 't2.marriedexemp')],
    [('t1.areacode', '==', 't2.areacode'), ('t1.salary', '==', 't2.salary'), ('t1.rate', '!=', 't2.rate')],
    [('t1.zip', '==', 't2.zip'), ('t1.salary', '==', 't2.salary'), ('t1.rate', '!=', 't2.rate')],
    [('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '<', 't2.singleexemp'), ('t1.marriedexemp', '>', 't2.marriedexemp')],
    [('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '>', 't2.singleexemp'), ('t1.marriedexemp', '<', 't2.marriedexemp')],
    [('t1.state', '==', 't2.state'), ('t1.haschild', '==', 't2.haschild'), ('t1.childexemp', '>', 't2.childexemp')],
    [('t1.state', '==', 't2.state'), ('t1.haschild', '==', 't2.haschild'), ('t1.childexemp', '<', 't2.childexemp')],
    [('t1.state', '==', 't2.state'), ('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '>', 't2.singleexemp')],
    [('t1.state', '==', 't2.state'), ('t1.maritalstatus', '==', 't2.maritalstatus'), ('t1.singleexemp', '<', 't2.singleexemp')],
]
